In [2]:
import numpy as np

# NUMPY BASICS


The Numpy Library in python is used to avoid the continuous and unoptimized(slow) use of python default datatypes(list, tuples etc) for larger data sets and perform quick operations without having the need to apply loops or traversals 


###     NumPy array as an object

A numpy array is an object that has the following main attributes :-




1. shape :- refers to the size of each dimension represented in tuple form


In [ ]:
#1 

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D.shape)   # (2, 3)



2. dtype :- refers to data type stored in the homogenous array


In [ ]:


#2
arr = np.array([1, 2, 3])
print(arr.dtype)  # int64

arr_mixed = np.array([1, 2.5, 3])
print(arr_mixed)  # [1.  2.5 3. ]
print(arr_mixed.dtype)  # float64 (all converted to float) each one is converted to higher data type



3. ndim  :- refers to the number of dimensions of the array


In [ ]:

#3
print(arr2D.ndim)    # 2



4. 
    1. size  :- 

        Returns the total number of elements in the entire NumPy array.

        Works for arrays of any shape or dimension.
 
    2. len(arr) :-
        
        Returns the length of the first dimension (i.e., number of rows in a 2D array).

        Equivalent to arr.shape[0].


In [31]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)   # Output: 6 (2 rows × 3 columns)

print(len(arr))   # Output: 2 (number of rows)

6
2


### OPERATOR OVERLOADING FOR NUMPY ARRAYS
Note: Operators are generally applied in the case when shape of two operand arrays is same, in other cases concepts of broadcasting are applied but they may fail


## 5. UNARY OPERATOR

In [8]:
a = np.array([-1, 0, 1])
print("Negation:", -a)           # [1 0 -1]


Negation: [ 1  0 -1]


## Methods of Initialization


In [11]:
import numpy as np

# 1. array :   Converts any sequential data type into nd array
arr1 = np.array([[1, 2], [3, 4]])
print("array:\n", arr1)

# 2. asarray : Does not convert if already an nd array
# The below is used  to demonstrate that asarray() works better if no conversion is needed
a = np.array([1, 2, 3])
b = np.asarray(a)
print(a is b)  # True — same object (no copy made)

a = np.array([1, 2, 3])
b = np.array(a)
print(a is b)  # False — different object (copy made)


arr2 = np.asarray([[5, 6], [7, 8]])
print("\nasarray:\n", arr2)




array:
 [[1 2]
 [3 4]]
True
False

asarray:
 [[5 6]
 [7 8]]


##### Use array() function when you need a guaranteed copy of the array
##### Use asarray() function when you don't need copy if the input is already an array

In [ ]:

# 3. arange()
arr3 = np.arange(0, 10, 2)
print("\narange:\n", arr3)

## USED FOR INITIALIZING AN ARRAY OVER A RANGE like range() function


arange:
 [0 2 4 6 8]



3.b linspace() : Unlike arange() it divides the array into n points(as passed) and we don't need to specify the step,
                 this is generally used to generate a series of points for plotting of smooth curves.(PSLP)

np.linspace(start, stop, num=50, endpoint=True)
num  : the number of divisions in the range [start,stop]
endpoint : this argument if true(default) ensures that stop is  included in the resultant array


In [ ]:

arr=np.linspace(0,10,100,endpoint=True) #including the end point
print(arr)
arr=np.linspace(0,10,1000,endpoint=False) #including the end point
print(arr)


In [ ]:

# 4. ones, ones_like
arr4 = np.ones((2, 3))# Used to initialize an array with all elements as ones for given shape
print("\nones:\n", arr4) 

arr5 = np.ones_like(arr1) # Used to generate an array with all values as ones with same shape as input array
print("\nones_like:\n", arr5)


In [ ]:

# 5. zeros, zeros_like
arr6 = np.zeros((2, 3))# Used to initialize an array with all elements as zeroes for given shape
print("\nzeros:\n", arr6)

arr7 = np.zeros_like(arr2)# Used to generate an array with all values as ones with same shape as input array
print("\nzeros_like:\n", arr7)


In [ ]:

# 6. empty, empty_like
arr8 = np.empty((2, 3)) # Initializes an array with garbage values for given shape
print("\nempty (uninitialized values):\n", arr8)

arr9 = np.empty_like(arr1)# Used to generate an array with all values as garbage with same shape as input array
print("\nempty_like (uninitialized values):\n", arr9)


In [ ]:

# 7. full, full_like
arr10 = np.full((2, 2), 9)# Initializes an array with input values for given shape
print("\nfull:\n", arr10)

arr11 = np.full_like(arr1, 7)# Used to generate an array with all values as input with same shape as input array
print("\nfull_like:\n", arr11)


In [ ]:

# 8. eye, identity
arr12 = np.eye(3)#Used to generate an identity matrix (n,n) shaped array for given n, where all arr[i][i]==1 for i in (0,n)  
print("\neye (identity matrix):\n", arr12)

arr13 = np.identity(3) # same as above
print("\nidentity:\n", arr13)


## numpy.random package 