In [1]:
import numpy as np

## INDEXING AND SLICING

#### Indexing and Slicing work pretty much the same in numpy arrays as in lists in python along with fewer new concepts.

## 1. FANCY INDEXING

Used to slice particular indexes(generally non-sequential) or limitedly sequential

In [ ]:
arr=np.array([10,20,30,40,50])

print(arr[[0,2,3]])#Pass a list within the index that contains indexes to be selected

[10 30 40]


## 2. BOOLEAN MASKING
Used to slice elements that meet certain conditions specified within braces.


#### Caution :
The Python keywords and and or do not work with Boolean arrays. Use & (and) and | (or) instead.

In [19]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

print(names=="Bob","\n")

print(data[names=="Bob"],"\n")

print(data[names=="Bob",1:],"\n")

print(data[names=="Bob",1],"\n")

print(data[(names=="Bob") | (names=="Will"),1],"\n")
print(data[(names=="Bob") | (names=="Will")])
# Alternative
# cond=(names=="Bob") | (names=="Will")
# print(data[cond])




[ True False False  True False False False] 

[[4 7]
 [0 0]] 

[[7]
 [0]] 

[7 0] 

[7 6 0 2] 

[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


## 3. INDEXING WITH SLICING(V.imp)


In [10]:
arr2d=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

print(arr2d[:2,1:]) 
'''
:2 selects the first two rows → [[1,2,3], [4,5,6]]
1: selects the columns from index 1 onward → [[2,3], [5,6]]
'''
print(arr2d[:2][1:])
'''
[:2] selects first two elements of array :-
array([[1, 2, 3],
       [4, 5, 6]])

[1:] selects the 2nd element onwards from above result
'''  

[[2 3]
 [5 6]]
[[4 5 6]]


'\n[:2] selects first two elements of array :-\narray([[1, 2, 3],\n       [4, 5, 6]])\n\n[1:] selects the 2nd element onwards from above result\n'