In [2]:
import numpy as np

# ARRAY MANIPULATION

## reshape()

Note : reshape() does not change or modify the actual/source array, it only creates a reshaped copy

In [ ]:


arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))  # 2 rows, 3 columns
print(reshaped)


# Automatically deciding dimension size
reshaped=arr.reshape((-1,2)) # Numpy will automatically decide the number of rows
print(reshaped)



#Output :
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


## ravel()

Returns a flattened view of the original array if possible.

No data is copied (i.e., it's a shallow copy), so changes in the raveled array may affect the original.

Faster and more memory-efficient.

In [3]:

##eg.

a=np.array([[1,2],[3,4]])

r=a.ravel() # Creates a shallow copy

r[0]=99

print(r)
print(a) # Changes are also reflected in a



[99  2  3  4]
[[99  2]
 [ 3  4]]


## flatten() 

Always returns a copy of the array (i.e., a deep copy).

Changes to the flattened array do not affect the original.

Slightly slower and uses more memory

In [ ]:
a=np.array([[1,2],[3,4]])

r=a.flatten() # Creates a true copy

r[0]=99

print(r)
print(a) # Changes are not reflected in a

[99  2  3  4]
[[1 2]
 [3 4]]
