In [4]:
import numpy as np
arr = np.array([
    [[2, 7, 3],
     [4, 1, 6],
     [0, 5, 8],
     [9, 2, 3]],

    [[6, 4, 0],
     [7, 1, 5],
     [8, 2, 9],
     [3, 6, 1]]
])

# Mathematical and Statistical Operations

## Element-wise-Operations


#### 1. ARITHMETIC OPERATORS


In [ ]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)          # [5 7 9]
print("Subtraction:", a - b)       # [-3 -3 -3]
print("Multiplication:", a * b)    # [4 10 18]
print("Division:", b / a)          # [4. 2.5 2.]
print("Modulus:", b % a)           # [0 1 0]
print("Power:", a ** 2)            # [1 4 9]
print("Square root:",np.sqrt(a))   # [1. 1.41421356 1.73205081]
print("Exponential :",np.exp(a))   # [ 2.71828183  7.3890561  20.08553692]
print("Logarithm :",np.log(a))     #  [0. 0.69314718 1.09861229]


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Modulus: [0 1 0]
Power: [1 4 9]
Square root: [1.         1.41421356 1.73205081]
Exponential : [ 2.71828183  7.3890561  20.08553692]
Logarithm : [0.         0.69314718 1.09861229]


## 2. COMPARISON OPERATORS



In [ ]:
 
print("Equal:", a == b)            # [False False False]
print("Not Equal:", a != b)        # [True True True]
print("Greater Than:", a > b)      # [False False False]
print("Less Than:", a < b)         # [True True True]


Equal: [False False False]
Not Equal: [ True  True  True]
Greater Than: [False False False]
Less Than: [ True  True  True]


## 3. LOGICAL OPERATORS
Use np.logical_and, np.logical_or, etc., or &, |, ~ for element-wise logic:

In [ ]:
x = np.array([True, False, True])
y = np.array([False, False, True])

print("Logical AND:", np.logical_and(x, y))    # [False False True]
print("Logical OR:", np.logical_or(x, y))      # [True False True]
print("Logical NOT:", np.logical_not(x))       # [False  True False]

# Equivalent using bitwise operators (on boolean arrays)
print("x & y:", x & y)                         # [False False  True]
print("x | y:", x | y)                         # [ True False  True]


Logical AND: [False False  True]
Logical OR: [ True False  True]
Logical NOT: [False  True False]
x & y: [False False  True]
x | y: [ True False  True]


## AGGREGATION OPERATIONS



 Aggregate functions :- They work as is for 1-D arrays and return single (int/float) values whereas for multi-dimensional arrays they work on flattened arrays unless axis is specified (concept of axis explained later).

    1. sum : Calculate sum across the flattened array / along the axis
    2. min : Calculate minimum value across the flattened array / along the axis 
    3. max : Calculate maximum value across the flattened array / along the axis
    4. mean : Calculate mean of values across the flattened array / along the axis
    5. std : Calculate standard deviation across the flattened array / along the axis.

In [ ]:


print("Without specifying axis (works on flattened array) :")
#a
print(np.sum(arr))

#b They work same as sum for axis
print(np.max(arr))
#c
print(np.min(arr))
#d
print(np.mean(arr))

#e
print(np.std(arr)) # Standard deviation


9
0
4.25
[[0 1 0 1]
 [2 1 1 2]]
[[3 0 2]
 [2 3 2]]
2.787621447279622


## Min/ Max Index Functions

1. argmin : Calculate indices with minimum value(s) across the flattened array / along the axis
2. argmax : Calculate indices with maximum value(s) across the flattened array / along the axis
3. where() :  Used to return an array with indices having elements matching particular condtions
4. nonzero()  : Returns indices of non-zero elements.

In [ ]:
#a
print(np.argmin(arr))

#b
print(np.argmax(arr))

#c
#Use case - 1 
a = np.array([10, 20, 30, 40])
b = np.where(a > 25, 1, 0) # syntax 1: np.where(<condition>,value_if_true,value_if_false)
print(b)  # Output: [0 0 1 1]

#Use-case - 2
idx = np.where(a > 25)
print(idx)         # Output: (array([2, 3]),)
print(a[idx])      # Output: [30 40]

#d
print(np.nonzero(a-10)) #Returns all non-zero indices

## CUMULATIVE FUNCTIONS

1. cumsum() : Returns a new array where each element is the sum of all previous elements (including itself).
2. cumprod() : Returns a new array where each element is the product of all previous elements (including itself).
3. diff() : Returns an array giving the difference between consecutive elements.

In [ ]:

# 1
a = np.array([1, 2, 3, 4])
print(np.cumsum(a))
# Output: array([ 1,  3,  6, 10])


#2 
a = np.array([1, 2, 3, 4])
print(np.cumprod(a))
# Output: array([ 1,  2,  6, 24])

#3 
a = np.array([10, 13, 17, 21])
print(np.diff(a))
# Output: array([3, 4, 4])  → [13-10, 17-13, 21-17]

[ 1  3  6 10]
[ 1  2  6 24]
[-4 -4 -3]
