## Concept of Axis :
Whenever we ought to calculate any aggregate function on an array with shape(a,b,c,d,....) along a particular axis n, the resultant will be of the shape will not have the nth parameter 

eg. if n=0, resultant will be of shape (b,c,d,...)
and if n=1, resultant will be if shape (a,c,d,...)


In [1]:
import numpy as np

In [2]:

#5 
# arr = np.arange(1,25).reshape(2,3,4)
# arr = np.random.randint(0, 10, size=(2, 4, 3))

arr = np.array([
    [[2, 7, 3],
     [4, 1, 6],
     [0, 5, 8],
     [9, 2, 3]],

    [[6, 4, 0],
     [7, 1, 5],
     [8, 2, 9],
     [3, 6, 1]]
])

print(arr)
#a 
print("With axis =0 , we do column wise sum operation")
print(np.sum(arr,axis=0))   

print("With axis =1 , we do row wise sum operation")
print(np.sum(arr,axis=1))   

print("With axis =2 , we do row wise sum operation")
print(np.sum(arr,axis=2))   

print("Without specifying axis (works on flattened array) :")
print(np.sum(arr))



[[[2 7 3]
  [4 1 6]
  [0 5 8]
  [9 2 3]]

 [[6 4 0]
  [7 1 5]
  [8 2 9]
  [3 6 1]]]
With axis =0 , we do column wise sum operation
[[ 8 11  3]
 [11  2 11]
 [ 8  7 17]
 [12  8  4]]
With axis =1 , we do row wise sum operation
[[15 15 20]
 [24 13 15]]
With axis =2 , we do row wise sum operation
[[12 11 13 14]
 [10 13 19 10]]
Without specifying axis (works on flattened array) :
102
