In [2]:
import numpy as np

#                                           BROADCASTING 

## CASES WHEN SHAPE OF THE OPERANDS IS NOT SAME :-

### CASE 1 :- BROADCASTING Works (Compatible Shapes)

Broadcasting is used when two arrays with unequal but compatible shapes are operated, as the name suggests we broadcast dimensions to equate the shape of two arrays.

Shapes that can be broadcasted into one another are called compatible shapes.

Rules for Broadcasting :-

Step 1 :- Write the shapes of both arrays together, check if the number of dimensions are equal or not, if not, broadcast ones to the left end of the shape with smaller dimension until equal. 
eg. (2,3) and (3,)    --->  (2,3) (1,3)

Step 2:- Start from right-most end of both shapes and compare the dimensions, corresponding dimensions are compatible only if both are equal or either one of them is one.

Step 3:- If all the corresponding dimensions are compatible then the shapes are compatible, you can fill values into broadcasted dimensions by analytical method.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])   # shape: (2, 3)
B = np.array([10, 20, 30])            # shape: (3,)

C = A + B
print(C)
# Output:
# [[11 22 33]
#  [14 25 36]]

a = np.array([[1], [2], [3]])  # shape: (3, 1)
b = np.array([[10, 20, 30, 40]])  # shape: (1, 4)
print(a)
print(b)

print(a + b)


[[11 22 33]
 [14 25 36]]
[[1]
 [2]
 [3]]
[[10 20 30 40]]
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


NOTE :- SCALARS ALWAYS BROADCAST 


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = 5

print(A + B)
# [[6 7]
#  [8 9]]


[[6 7]
 [8 9]]


## newaxis() method in NumPy

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6,7])
try:
    print(A-B)
except Exception as e:
    print(f"{A} - {B} \nthrows:")
    print(e)

print("\nWe expect the dimesions to broadcast automatically ")
print(f"The shape of A is {A.shape}")
print(f"The shape of B is {B.shape}")
print("The dimensions are incompatible, therefore we need to introduce another dimension manually")

print(f"Using the new axis function on A :\n {A[:,np.newaxis]} \n Shape of A :{A[:,np.newaxis].shape}")
print()
print(f"Using the new axis function on B : {B[np.newaxis,:]} \n Shape of B :{B[np.newaxis,:].shape}")
A=A[:,np.newaxis]
B=B[np.newaxis,:]
print(f"A-B :\n {A-B}")

'''
[1 2 3] - [4 5 6 7] 
throws:
operands could not be broadcast together with shapes (3,) (4,) 

We expect the dimesions to broadcast automatically 
The shape of A is (3,)
The shape of B is (4,)
The dimensions are incompatible, therefore we need to introduce another dimension manually
Using the new axis function on A :
 [[1]
 [2]
 [3]] 
 Shape of A :(3, 1)

Using the new axis function on B : [[4 5 6 7]] 
 Shape of B :(1, 4)
A-B :
 [[-3 -4 -5 -6]
 [-2 -3 -4 -5]
 [-1 -2 -3 -4]] 
'''
