In [1]:
import numpy as np

## 4. MATRIX OPERATIONS


In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[5, 6], [7, 8]])
print(B)


### Dot Product

In [ ]:

# Dot product:  @ operator
print("Matrix Multiplication :" ,A @ B)



### Transpose

In [7]:

# Transpose: np.transpose(arr,axis)
print(f"Transpose of A :{np.transpose(A)}")


Transpose of A :[[1 3]
 [2 4]]


### Inverse

In [ ]:
# For many operations we use the linalg sub-package in numpy
# Inverse: np.linalg.inv()
print(f"Inverse of A {np.linalg.inv(A)}")


### Determinant & Eigenvalues

In [ ]:

# Determinant: np.linalg.det()
print(f"Determinant of A :{np.linalg.det(A)}")


In [ ]:

# Eigenvalues/vectors: np.linalg.eig()
# Use when required


### SOLVING A SYSTEM OF LINEAR EQN.

Using np.linalg.solve() function we can solve a system of equations AX = B , where A is a square matrix and has square no. of variables as contained by X which is a column matrix. B has the same dimensions as that of X.

In [ ]:
A=np.array([[1,10,3],[1,9,4],[2,3,6]])
B=np.array([5,9,10])
X=np.linalg.solve(A,B)
print(X)


[-7.  0.  4.]


### TRACE OF A MATRIX
Sum of all the diagonal elements.

In [5]:
Trace=np.trace(A)
print(A)
print(Trace)

[[ 1 10  3]
 [ 1  9  4]
 [ 2  3  6]]
16
