In [21]:
import numpy as np

# RESHAPING AND MANIPULATION OF ARRAYS
 
There are 3 major operations in this section :- `np.reshape()` , `np.ravel()` , `np.flatten()`

---
## `.reshape()`
It is used to transform the array into a new array with same values arranged differently across dimensions of new shape.

**Syntax :** `array_name.reshape(new_shape)`

⚠️ **Caution**: The size of array should be equal to the product of all the dimensions of the new shape.(eg shown below)

📝 **Note**: It does not change or modify the actual/source array, it only creates a reshaped copy

In [22]:


arr1 = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr1.reshape((2, 3))  # 2 rows, 3 columns
print(reshaped,end="\n\n")
try:
    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    reshaped = arr.reshape((2, 3))  # 2 rows, 3 columns
    print(reshaped)
except Exception as e:
    print(f"Following exception thrown upon running:\n\tarr = np.array([1, 2, 3, 4, 5, 6]) \n\treshaped = arr.reshape((2, 3))\n\treshaped = arr.reshape((2, 3))\n\nException: {e}")


# Automatically deciding dimension size
reshaped=arr1.reshape((-1,2)) # Numpy will automatically decide the number of rows
print("\n",reshaped)



#Output :
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]

Following exception thrown upon running:
	arr = np.array([1, 2, 3, 4, 5, 6]) 
	reshaped = arr.reshape((2, 3))
	reshaped = arr.reshape((2, 3))

Exception: cannot reshape array of size 7 into shape (2,3)

 [[1 2]
 [3 4]
 [5 6]]


---
## `.ravel()`

Returns a flattened view of the original array if possible.

**Syntax :** `array_name.ravel()`

📝 **Note :** No data is copied (i.e., it's a shallow copy), so changes in the raveled array may affect the original.

Faster and more memory-efficient.

In [23]:

##eg.

a=np.array([[1,2],[3,4]])

r=a.ravel() # Creates a shallow copy

r[0]=99

print(r)
print(a) # Changes are also reflected in a



[99  2  3  4]
[[99  2]
 [ 3  4]]


---
## `.flatten()` 

Always returns a copy of the array (i.e., a deep copy).

**Syntax :** `array_name.flatten()`

📝 **Note**: Changes to the flattened array do not affect the original.

Slightly slower and uses more memory

In [24]:
a=np.array([[1,2],[3,4]])

r=a.flatten() # Creates a true copy

r[0]=99

print(r)
print(a) # Changes are not reflected in a

[99  2  3  4]
[[1 2]
 [3 4]]


###  DIFFERENCE B/W `.ravel` AND `.flatten`