In [4]:
import numpy as np

# AXIS OPERATIONS

Operations involving manipulation around the axis of the array.

Mainly two operations :- `np.swapaxes()` , `np.moveaxis() (⭐⭐⭐)`

---

## `np.swapaxes()`

It is used to interchange(swap) the dimensions of the axes passed as arguments. 

**Syntax :** `np.swapaxes(array_name,first_Axis,second_Axis)`

eg.

In [5]:
arr = np.array([[[1, 2], [3, 4]]])  
print(f"Original Array :\n{arr}")
print(f"Shape of above array : {arr.shape}")# Shape: (1, 2, 2)
swapped = np.swapaxes(arr, 0, 1)
print(f"Swapped Array :\n{swapped}")
print("Swapped shape:", swapped.shape)   # Shape: (2, 1, 2)

Original Array :
[[[1 2]
  [3 4]]]
Shape of above array : (1, 2, 2)
Swapped Array :
[[[1 2]]

 [[3 4]]]
Swapped shape: (2, 1, 2)


--- 
## `np.moveaxis()` [more functional]

**Syntax :** `np.moveaxis(array, source, destination)`

source: index(es) of the axis you want to move.

destination: where you want that axis to go.

📝 **Note** : It does not modify the array in place — it returns a view with the axes moved.

Following are some examples :-

---

### Example 1: Move a single axis

In [6]:
arr = np.zeros((3, 4, 5))  # Shape: (3, 4, 5)

# Move axis 0 (first) to the end
moved = np.moveaxis(arr, 0, -1)

print(moved.shape)  # (4, 5, 3)

(4, 5, 3)


---  
### Example 2: Move axis 2 to position 0

In [7]:
arr = np.ones((2, 3, 4))  # Shape: (2, 3, 4)

moved = np.moveaxis(arr, 2, 0)

print(moved.shape)  # (4, 2, 3)

(4, 2, 3)


---
### Example 3: Move multiple axes

In [8]:
arr = np.random.rand(2, 3, 4, 5)  # Shape: (2, 3, 4, 5)

# Move axes 0 and 3 to positions 2 and 0
moved = np.moveaxis(arr, [0, 3], [2, 0])

print(moved.shape)  # (5, 3, 2, 4)


(5, 3, 2, 4)
